name: hackweek
channels:
  - conda-forge
  - defaults
  - omfit
  - aaronkho
dependencies:
  - python=3.7
  - jupyter
  - numpy=1.20
  - scipy=1.6
  - matplotlib=3.4
  - pandas=1.2
  - xarray=0.18
  - astropy=4.2
  - plasmapy=0.6
  - pytest=6.2
  - hypothesis=6.14
  - h5py=3.2
  - pip=21.1
  - tofu
  - omas
  - xbout
  - omfit-opt-deps=3.2021.20
  - omfit_classes
  - pip:
    - turbopy
    - freegs
    - bapsflib
