name: hackweek
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.10
  - jupyter
  - numpy=1.20.0
  - scipy=1.7.0
  - matplotlib=3.4.2
  - pandas=1.2.5
  - xarray=0.18.2
  - astropy=4.2.1
  - sunpy=3.0.0
  - plasmapy=0.6.0
  - pytest=6.2.4
  - hypothesis=6.14
  - h5py=3.2.1
  - pip=21.1.3
  - tofu
  - omas
  - xbout
  - aurorafusion
  - astroquery
  - pip:
    - turbopy
    - freegs
    - bapsflib
    - divHretention>=0.1
